[package]
name = "raytracinginaweekend"
version = "0.1.0"
authors = ["Oliver Goding <olivergoding@gmail.com>"]

[dependencies]
rand = "0.5.0"
time = "0.1.40"
xorshift = "0.1.3"
#image = "0.19.0"
if_chain = "0.1.2"
#lazy_static = "1.0.1"
rayon = "1.0.2"

[profile.release]
debug = true